[build]
  publish = "_site"
  command = ""

[[plugins]]
package = "./plugins/keep-data-cache"

[[headers]]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "https://speedlify.netlify.app"
  to = "https://www.speedlify.dev"
  status = 301
  force = true
